# Generated by Django 3.0.8 on 2020-07-20 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200720_0314'),
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column', to='boards.Board'),
        ),
    ]
