# Generated by Django 3.0.8 on 2020-07-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200720_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lead_time',
            field=models.DateTimeField(null=True, verbose_name='Date of assignment'),
        ),
    ]
